on: "3.8"
services:
    piped:
          image: ghcr.io/team-piped/piped:latest
              ports:
                      - "${PIPED_PORT}:8080"
                          environment:
                                  HTTP_PORT: 8080
                                        DB_USER: piped
                                              DB_PASSWORD: "${DB_PASSWORD}"
                                                    DB_HOST: postgres
                                                          DB_PORT: 5432
                                                                DB_NAME: piped
                                                                    depends_on:
                                                                            postgres:
                                                                                      condition: service_healthy

                                                                                        postgres:
                                                                                              image: postgres:13-alpine
                                                                                                  environment:
                                                                                                          POSTGRES_USER: piped
                                                                                                                POSTGRES_PASSWORD: "${DB_PASSWORD}"
                                                                                                                      POSTGRES_DB: piped
                                                                                                                          volumes:
                                                                                                                                  - ./data/postgres:/var/lib/postgresql/data
